steps:
  # Step 1: Checkout the source code from GitHub
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/mdrdani/GO-lekduit", "src"]

  # Step 2: Build the container image using Docker
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/lekduit", "src"]

  # Step 3: Push the container image to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/lekduit"]

images:
  # Define the container image to be pushed to Artifact Registry
  - "gcr.io/$PROJECT_ID/lekduit"
